### PR TITLE
Nsidc access

### PR DESCRIPTION
**Pull request by asteiker**
Final updates to nsidc access tutorial

### CODE REVIEW

**Comment by scottyhq** [comment]
@asteiker jupyterbook is picky about markdown headings, they have to be ordered sequentially:
```
# title (only one)
## subtitle
### susubtitle
## subtitle
```

**Comment by scottyhq** [comment]
the log shows `Exception: File `'./scripts/nsidc-download_SNEX20_SD.001.py'` not found.`

**Comment by asteiker** [comment]
@scottyhq added the scripts folder- sorry for missing this earlier.

**Comment by scottyhq** [comment]
@asteiker I'm going to merge this, it's not going to render on the website as currently set up b/c of the way the credentialing is currently done: `[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.` 

Can sort that out later if you want

**Review by scottyhq — APPROVED** [review]

**Comment by asteiker** [comment]
@scottyhq Thanks - I was wondering how it would render with the credential inputs. Happy to try to sort out later.

**Pull request merged**
