### PR TITLE
GitHub deploy - Increase AWS S3 key timeout

### LINKED ISSUE #115: UAVSAR tutorial plots not rendering
For some reason, although only a few sentences of text only was changed on the last pull request, most of the plots on the UAVSAR tutorial are no longer rendering.

### PR DESCRIPTION
**Pull request by jomey**
Building the book from scratch can take up to 40 mins during a GitHub
deploy via GitHub actions. This exceeds the the initially requested token
validity periond from AWS S3. Setting the new limit to this max period.

Fixes #115

### CODE REVIEW

**Review by hpmarshall — APPROVED** [review]
time out change - nice find Joe!

**Comment by scottyhq** [comment]
thanks @jomey . note I;d intended to merge a change earlier today but got sidetracked that should only execute notebooks that have been changed rather than all of them every time. This will vastly cut down on execution time:

https://github.com/snowex-hackweek/website/blob/141a57dae13dd6e633c787728a9d831fdf8ab279/book/_config.yml#L30

From a security standpoint you want credentials to last only as long as necessary. I'll go ahead and merge this, but we can reduce the number if caching improves things.

**Comment by scottyhq** [comment]
One tricky thing with notebooks relying on network access to data is that requests can hang, so there is some unpredictability in the build time

**Comment by jomey** [comment]
I am aware of the security considerations. 

Given the access restrictions to the GitHub actions environment, I still see the increase of the key lifetime as no reduction in security. The running docker image is removed immediately after the build is complete and the token is no longer accessible. As you noted, there is a lot of uncertainty regards network issues or current load on the GitHub actions infrastructure.

**Pull request merged**
