### PR TITLE
Preliminarily - Update Git and GitHub

### PR DESCRIPTION
**Pull request by jomey**
Update images with SnowEx GH page. Also re-word to distinct between Git
and GitHub.

### CODE REVIEW

**Review by scottyhq — APPROVED** [review]

**Comment by scottyhq** [comment]
thanks @jomey, the new images look great and i like the additions and simplifications to the text!

**Comment by jomey** [comment]
Thank you Scott.

For a bit more context - I want to flesh out the preliminary pages a bit more over the next week or two. Goal is to have enough content for participants to do a self-guided first 'technical setup' check. Hopefully this can be written that everyone can follow independent on how deep their background is.

**Comment by scottyhq** [comment]
Sounds good! I also have some organizational updates I'll push today and would like to get a few more tutorial notebooks posted. You should have merge permissions in this repo, so you'll also be able to merge changes if you'd like. I do like the procedure of 1. add the 'preview' label to get a link to a rendered preview, and 2. get one more set of eyes before merging. But if they are simple changes we can bypass that.

**Comment by jomey** [comment]
Feel free to add me to any of these as a reviewer. Can go over any ones you like a second pair of eyes on first thing tomorrow morning.

Also good to know about the tags. Will keep them in mind for any reviews.

**Pull request merged**
