### PR TITLE
Add draft of LIS tutorial

### PR DESCRIPTION
**Pull request by bmcandr**
This PR adds a draft of the LIS tutorial. We'll be adding the comparison section and an additional notebook with an example of an interactive dashboard next week.

Access to our S3 bucket is not yet set up so the preview will fail until we have that established. Will be in touch next week about this.

### CODE REVIEW

**Comment by scottyhq** [comment]
Awesome! Had a quick look and am super impressed with this @bmcandr ! 

> Access to our S3 bucket is not yet set up so the preview will fail until we have that established. Will be in touch next week about this.

We can sort this out via Slack, there are a few options depending on the dataset size and permissions. You might be interested in this repository as a demo for smallish tutorial datasets https://github.com/scottyhq/zarrdata

**Comment by bmcandr** [comment]
Thanks @scottyhq, I'll check that out! I'll hop on Slack next week to sort this out.

Looks like we're also failing a link check?
```
(tutorials/lis/index: line 100012) broken    https://www.wcc.nrcs.usda.gov/snow/ - HTTPSConnectionPool(host='www.wcc.nrcs.usda.gov', port=443): Max retries exceeded with url: /snow/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))
```

**Comment by scottyhq** [comment]
@bmcandr the preview rendering is now working! Let's try to merge this today or tomorrow. It's looking really good except for a few remaining 'TODO' sections

**Review by mlwrzesien — COMMENTED** [review]
I'm still very new to GitHub, especially collaborating on someone else's branch. But I only had minor text edits here, which I think I successfully pushed to Brendan's branch?

Everything looks good to me. Big thanks to both Brendan for basically building our entire notebook and to Scott for all the help along the way.

**Comment by scottyhq** [comment]
> But I only had minor text edits here, which I think I successfully pushed to Brendan's branch?

Excellent!  thanks @mlwrzesien ! Just don't forget to 'Kestart kernel and clear all outputs' so that we get a clean notebook submitted. 

In the preview link looks like two images are missing at the top of the notebook. And there are still two 'todo' sections '(LIS (raster) vs. SNOTEL (point)' and 'Exercises'. If you want we can leave those out of this pull request and you can follow up with a separate one to add more content. I think the content you already have is excellent! 

One last note. Not all interactivity will be available on the rendered website (but will when people run this notebook on a jupyterhub). Single images give interactive cursor feedback on the website, but time sliders and extra widgets won't work without a fair amount of extra work https://discourse.holoviz.org/t/tips-for-saving-interactive-plots-as-html/175

**Comment by mlwrzesien** [comment]
Hmm, I see the figures on our daskhub. Let me see if I can figure that out and then submit a new commit. And I'll remove the "to do" sections for now.

I think Brendan is out of the office today, but I'll leave it up to him about the interactive options. Perhaps we can leave them and explain to the participants how to use them if they open up the notebook. But I'm happy either way

**Review by mlwrzesien — COMMENTED** [review]
I believe I fixed the image issue. I've also removed some text, but I did keep the LIS vs SNOTEL section as a reminder that we want to try to include that for the tutorial, but we'll see.

When reviewing the files changed, it brings up a lot more than the ones in our tutorial. I'm not sure if that's something I did incorrectly on my end? I looked at other tutorials for examples on how to get the images to display. Let me know if I need to do anything about those files!

Also, as far as I'm aware, I did restart the kernal and cleared all variables. But again, I'm very new to Jupyter notebooks/dask hub. If I messed anything up, I should be able to fix it before end of the day!

**Review by scottyhq — APPROVED** [review]
Thank you @mlwrzesien and @bmcandr this looks great! I'm going to merge it in. If you want to make further modifications we can do that in a separate pull request

**Pull request merged**
