### PR TITLE
Camera tutorial updates

### PR DESCRIPTION
**Pull request by catherine-m-breen**
new tutorial for time-lapse tutorial on thursday july 15

### CODE REVIEW

**Comment by scottyhq** [comment]
see failing checks @catherine-m-breen you need to clear the notebooks of output before submitting (`timelapse-camera-tutorial.ipynb cell 21: execution count` 

Also since you changed the name of the notebook you'll have to update the table of contents: `/home/jovyan/book/tutorials/day_4.md:7: WARNING: toctree contains reference to nonexisting document 'tutorials/camera-traps-tutorial/camera-traps-notebook'`

**Comment by catherine-m-breen** [comment]
> see failing checks @catherine-m-breen you need to clear the notebooks of output before submitting (`timelapse-camera-tutorial.ipynb cell 21: execution count`
> 
> Also since you changed the name of the notebook you'll have to update the table of contents: `/home/jovyan/book/tutorials/day_4.md:7: WARNING: toctree contains reference to nonexisting document 'tutorials/camera-traps-tutorial/camera-traps-notebook'`

Katie note: Thank you for the tip on TOC. I should have fixed that now. I also cleared the kernel.

**Comment by jomey** [comment]
Looks like you have cloned the ` github_setup_check` inside the webfolder and committed that.
Could you remove this again?
A simple
```shell
rm -rf  github_setup_check
```
of the folder followed by a commit should do it.

**Review by jomey — APPROVED** [review]

**Comment by aaarendt** [comment]
For the folium map code block, I learned about tags for the first time. It looks like this needs to be added as cell metadata, and not as code within the block? It took me a long time to figure out that cell metadata is accessed on the little gears button, upper right side of Jupyter Lab. But I still didn't succeed in getting this to work!

**Comment by aaarendt** [comment]
Otherwise this looks great and I think we can merge it.

**Review by aaarendt — APPROVED** [review]

**Comment by scottyhq** [comment]
@catherine-m-breen couple requests: 

- could you please remove the bold formatting for your title?  `# **Time-lapse Cameras and Snow Applications**`
- you have a repeat header `## Time-lapse Camera Applications` (can remove the second)

**Comment by catherine-m-breen** [comment]
> @catherine-m-breen couple requests:
> 
> * could you please remove the bold formatting for your title?  `# **Time-lapse Cameras and Snow Applications**`
> * you have a repeat header `## Time-lapse Camera Applications` (can remove the second)
> * `aws s3 sync --no-progress s3://snowex-data/tutorial-data/camera-trap/ /tmp/camera-trap` currently pulls 4.3GB of data. can we keep this small (using `aws s3 cp` to get only images you display and work with later in the notebook?



> @catherine-m-breen couple requests:
> 
> * could you please remove the bold formatting for your title?  `# **Time-lapse Cameras and Snow Applications**`
> * you have a repeat header `## Time-lapse Camera Applications` (can remove the second)
> * `aws s3 sync --no-progress s3://snowex-data/tutorial-data/camera-trap/ /tmp/camera-trap` currently pulls 4.3GB of data. can we keep this small (using `aws s3 cp` to get only images you display and work with later in the notebook?

**Comment by scottyhq** [comment]
thank you @catherine-m-breen and @cassielumbrazo looks great!

**Comment by scottyhq** [comment]
i accidentally merged this in w/o checking that the notebook was cleaned of output :( will try to remedy after tmrw's session. it's not a big issue (renders fine on the website, but does add bloat to the total repo size). Need to fix the CI a bit...

**Comment by jomey** [comment]
Let me know if you need help on this.
One note regards the repo size - Once committed you will have a hard time reducing that again without changing the original commit, which complicates the effort.
Maybe we can just leaves this as is for the hackweek to reduce potential major merge conflicts with participants and have a look at the end of the week regards the repository size.

**Pull request merged**
