### PR TITLE
enable google analytics

### LINKED ISSUE #4: add google analytics and link checking workflows
described in these docs: https://jupyterbook.org/advanced/html.html#advanced-html-outputs

### PR DESCRIPTION
**Pull request by scottyhq**
closes #4

### CODE REVIEW

**Comment by scottyhq** [comment]
wish this was working during the event :) confirmed it works with these changes: 
Screen Shot 2021-09-02 at 12 35 27 PM

**Review by jomey — APPROVED** [review]
Interesting to see Googles recommendation to put this in the header and before the body tag. I am used to having lazily loaded tracking via Javascript in the footer of a page. This will enable the browser to first take care of the HMTL and JS of the site, before processing any third-party JS.

**Comment by jomey** [comment]
Also checked and the Google Analytics request showed up for me on the test deployment, after loading the page.

**Comment by jomey** [comment]
> wish this was working during the event :) confirmed it works with these changes:
> Screen Shot 2021-09-02 at 12 35 27 PM

100% agree that this would have been a nice metric to know and add for the event.

**Pull request merged**
